server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=Asia/Seoul
    username: postgres
    password: 1234

mybatis:
  type-aliases-package : com.blucean.solution.**.dto

blucean:
  file:
    board: 'C:/fileUpload'