server:
  port: 8090

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/postgres?serverTimezone=Asia/Seoul
    username: postgres
    password: 1234
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

mybatis:
  type-aliases-package : com.blucean.solution.**.dto

blucean:
  file:
    board: 'C:/fileUpload'